Models/ErrorViewModel.cs
namespace easyflight_mvc_dotnet_razor.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/AutocompleteController.cs
using easyflight_mvc_dotnet_razor.Libraries;
using Microsoft.AspNetCore.Mvc;

namespace easyflight_mvc_dotnet_razor.Controllers
{
    [Route("api/[controller]")]
    public class AutocompleteController : Controller
    {

        [HttpGet("{query}")]
        async public Task<AmadeusApiSdkLocationsResponseModel> Get(string query)
        {

            DotNetEnv.Env.Load();
            string apiKey = DotNetEnv.Env.GetString("API_KEY");
            string apiSecret = DotNetEnv.Env.GetString("API_SECRET");

            AmadeusApiSdk amadeusApiSdk = new AmadeusApiSdk(apiKey, apiSecret);
            return await amadeusApiSdk.AirportAndCitySearch(query);
        }

    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using easyflight_mvc_dotnet_razor.Models;

namespace easyflight_mvc_dotnet_razor.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/SearchOriginDestinyController.cs
using System.Net.Http.Headers;
using easyflight_mvc_dotnet_razor.Libraries;
using Microsoft.AspNetCore.Mvc;

namespace easyflight_mvc_dotnet_razor.Controllers
{
    public class SearchOriginDestinyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> ConfirmOrigin(String inputOrigin)
        {
            AmadeusApiSdk amadeusApiSdk = new AmadeusApiSdk("UL3RwPkrJWESRaL6ZwWciQeEUZ772G8X", "I5rRCeudc9BzRUOM");
            //string data = await amadeusApiSdk.AirportAndCitySearch();
            ViewBag.data = "";
            return View();
        }

        public IActionResult Destiny()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/SearchOriginDestiny/ConfirmOrigin.cshtml
@{
    ViewData["Title"] = "Search Origin";
}
<h1>¿Where do you want to flight?</h1>

<nav aria-label="breadcrumb" class="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active">Step 1 - Origin</li>
        <li class="breadcrumb-item">Step 2 - Destiny</li>
        <li class="breadcrumb-item">Step 3 - Data</li>
    </ol>
</nav>

<form class="form-search" asp-action="Destiny">
    <h1 class="h3 mb-3 font-weight-normal">Confirm your origin city</h1>
    <ul>
        <li>@ViewBag.data</li>
    </ul>
    <br />
    <button class="btn btn-lg btn-primary btn-block" type="submit">Next step</button>
</form>

Views/SearchOriginDestiny/Destiny.cshtml
@{
    ViewData["Title"] = "Flight Search";
}
<h1>¿Where do you want to flight?</h1>

<nav aria-label="breadcrumb" class="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active">Step 1 - Origin</li>
        <li class="breadcrumb-item active">Step 2 - Destiny</li>
        <li class="breadcrumb-item">Step 3 - Data</li>
    </ol>
</nav>

<form class="form-search">
    <h1 class="h3 mb-3 font-weight-normal">Step 2 - Destiny</h1>
    <label for="inputDestiny" class="sr-only">Destiny</label>
    <input type="text" id="inputDestiny" class="form-control" placeholder="Type destiny city" required/>
    <br/>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Next step</button>
</form>

Views/SearchOriginDestiny/Index.cshtml
@{
    ViewData["Title"] = "Search Origin";
}
<h1>¿Where do you want to go?</h1>

<nav aria-label="breadcrumb" class="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active">Step 1 - Flight information</li>
        <li class="breadcrumb-item">Step 2 - Destiny</li>
        <li class="breadcrumb-item">Step 3 - Data</li>
    </ol>
</nav>

<div class="row">
    <div class="col col-12 col-4 col-sm-12 col-md-8 col-lg-5">
        <form class="form-search" asp-action="ConfirmOrigin">
            <h1 class="h3 mb-3 font-weight-normal">Flight information</h1>
            <label for="inputOrigin" class="sr-only">Origin</label>
            <input type="text" id="inputOrigin" name="inputOrigin" class="form-control form-control-sm autocomplete" placeholder="Type origin city" required autofocus />
            <br />

            <label for="inputDestiny" class="sr-only">Destiny</label>
            <input type="text" id="inputDestiny" name="inputDestiny" class="form-control form-control-sm autocomplete" placeholder="Type destiny city" required />
            <br />

            <div class="row">
                <div class="col">
                    <label for="departureDate" class="sr-only">Departure date</label>
                    <input type="date" id="departureDate" name="departureDate" class="form-control form-control-sm" required />
                </div>
                <div class="col">
                    <label for="returnDate" class="sr-only">Return date (Optional)</label>
                    <input type="date" id="returnDate" name="returnDate" class="form-control form-control-sm" />
                </div>
            </div>
            <br />

            <div class="row">
                <div class="col">
                    <label for="adults" class="sr-only">Passengers <br />(adults)</label>
                    <select name="adults" id="adults" class="form-control form-control-sm">
                        <option value="1" selected>1</option>
                        @for (int n = 2; n <= 9; n++)
                        {
                            <option value="@n">@n</option>
                        }
                    </select>
                </div>
                <div class="col">
                    <label for="children" class="sr-only">Passengers <br />(children)</label>
                    <select name="children" id="children" class="form-control form-control-sm">
                        <option value="">No children</option>
                        @for (int n = 1; n <= 9; n++)
                        {
                            <option value="@n">@n</option>
                        }
                    </select>
                </div>
                <div class="col">
                    <label for="infants" class="sr-only">Passengers <br />(infants)</label>
                    <select name="infants" id="infants" class="form-control form-control-sm">
                        <option value="">No infants</option>
                        @for (int n = 1; n <= 9; n++)
                        {
                            <option value="@n">@n</option>
                        }
                    </select>
                </div>
            </div>
            <br />

            <button class="btn btn-sm btn-primary btn-block" type="submit">Search flights</button>
        </form>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Easy Flights</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="SearchOriginDestiny" asp-action="Index">Easy Flights</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SearchOriginDestiny" asp-action="Index">Flight Search</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Easy Flights
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>